name: deploy my web learning blog
on:
  push:
    braches:
      - master
permissions:
      contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
            publish_branch: gh-pages